Repository aperowebnancy/aperowebnancy-website, pull requests merged in 2020-10, with the labels that each got.

#44 Page 404 en cas d'erreur
  pages/404.js
Labels: RFR

#45 Improve 404 integration seo
  next-sitemap.js
  package.json
  pages/404.js
  yarn.lock
Labels: RFR

#47 refacto <svg /> icon
  components/Footer.js
  components/Header.js
  components/Icons.js
  components/Seo.js
  components/SpeakerLinks.js
  lib/requestMdxFiles.js
  pages/404.js
  pages/index.js
  pages/speakers.js
  pages/talks.js
  pages/talks/[slug].js
  scripts/build-rss.js
Labels: RFR

#49 Improve perf seo accebility
  pages/_app.js
  pages/speakers.js
Labels: RFR

#50 Bootstrap integration test with jest and react-testing-library
  .babelrc
  .eslintrc.json
  README.md
  __tests__/[slug].spec.js
  __tests__/index.spec.js
  __tests__/talks.spec.js
  jest.config.js
  package.json
  pages/404.js
  pages/_app.js
  pages/index.js
  setupTests.js
  speakers/fabien-casters.mdx
  yarn.lock
Labels: WIP

#51 Add test on github action
  .github/workflows/test.yml
Labels: WIP

#48 Design liste des talks
  package.json
  pages/_app.js
  pages/talks.js
  styles/sass/abstracts/_mixins.scss
  styles/sass/abstracts/_variables.scss
  styles/sass/abstracts/mixins/_breakpoints.scss
  styles/sass/abstracts/mixins/_colors.scss
  styles/sass/abstracts/mixins/_spacing.scss
  styles/sass/abstracts/vars/_breakpoints.scss
  styles/sass/abstracts/vars/_colors.scss
  styles/sass/abstracts/vars/_spacing.scss
  styles/sass/abstracts/vars/_transitions.scss
  styles/sass/atomes/card.scss
  styles/sass/components/talks-list.scss
  styles/sass/main.scss
  yarn.lock
Labels: design, feature

#53 Amélioration de la doc sur la verstion de Node + fix test
  .github/CONTRIBUTING.md
  .nvmrc
  __tests__/talks.spec.js
Labels: RFR

#55 Tests fail locally when the French dates are displayed
  package.json
  yarn.lock
Labels: RFR

#54 Display the number of web mentions in the talk page
  __tests__/[slug].spec.js
  components/WebMentionCounter.js
  components/Youtube.js
  pages/talks/[slug].js
Labels: RFR

#57 Ajout des webmentions sur la page d'un talk
  __tests__/[slug].spec.js
  components/Icons.js
  components/WebMentionCounter.js
  components/WebMentionCounter.spec.js
  components/WebMentions.js
  components/WebMentions.spec.js
  jest.config.js
  jest.global.js
  jest.setup.js
  lib/mocks/handlers.js
  lib/mocks/server.js
  package.json
  pages/talks/[slug].js
  setupTests.js
  yarn.lock
Labels: WIP

#58 Traduction et simplification des différents template
  .github/ISSUE_TEMPLATE/01_bug_report.md
  .github/ISSUE_TEMPLATE/02_feature_request.md
  .github/ISSUE_TEMPLATE/03_question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: RFR

#60 Suppression de l'icone Speakers lorsque les speakers ne sont pas renseignés
  __tests__/index.spec.js
  pages/index.js
Labels: RFR
